agent_name = "daily-pstn-call-transfer"
image = "your_username/daily-pstn-call-transfer:0.1"
image_credentials = "your_dockerhub_image_pull_secret"
secret_set = "daily-pstn-secrets"

[scaling]
	min_agents = 1
