[project]
name = "smallwebrtc-example"
version = "0.1.0"
description = "Example for building voice AI bots with Pipecat built using SmallWebRTC"
requires-python = ">=3.10"
dependencies = [
    "pipecat-ai[webrtc,silero,deepgram,openai,cartesia,runner]>=0.0.86",
    "pipecatcloud>=0.2.4"
]

[dependency-groups]
dev = [
    "ruff~=0.12.1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]