agent_name = "plivo-chatbot-dial-out"
image = "your_username/plivo-chatbot-dial-out:0.1"
image_credentials = "your_dockerhub_image_pull_secret"
secret_set = "plivo-chatbot"

[scaling]
	min_agents = 1
