agent_name = "telnyx-chatbot-dial-out"
image = "your_username/telnyx-chatbot-dial-out:0.1"
image_credentials = "your_dockerhub_image_pull_secret"
secret_set = "telnyx-chatbot"

[scaling]
	min_agents = 1
